### ISSUE TITLE
Regarding cookies and captcha

### ISSUE THREAD

**Issue by maiestro21** [tropicoo/zoneh#1]
I am trying to understand  the code of your bot.
How do you bypass the captcha? How do you generate phpsessid and zhe cookies ?

Thank you

**Comment by tropicoo** [comment]
- During scraping captcha image is sent to the Telegram and user needs to solve it by typing captcha characters.
- zhe-cookies are generated by evaluating returned js-functions
`[value = js2py.eval_js('\n'.join([js_aes_slow, js_funcs]))]`

**Comment by maiestro21** [comment]
I tested the bot and it never asked for captcha, somehow it just works and bypass it.

**Comment by tropicoo** [comment]
It seems that you didn't hit it yet. It's a matter of time.

**Comment by tropicoo** [comment]
I also recommend to set much higher values in this code block because Zone-H will ban your IP-address for several months due to frequent scrapings.
```python
def sleep_time():
    """
    Lowering the values increases the risk of getting perm banned by Zone-H's
    anti-DDoS logic.
    """
    return secrets.choice(range(4, 7))
```
